-- Sentinel-X Database Schema
-- PostgreSQL

CREATE TABLE IF NOT EXISTS cameras (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    location VARCHAR(200) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ONLINE'
);

CREATE TABLE IF NOT EXISTS watchlist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number VARCHAR(20) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    description VARCHAR(250) NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS ix_watchlist_plate_number
    ON watchlist (plate_number);


CREATE TABLE IF NOT EXISTS detections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_id INTEGER NOT NULL,
    plate_number VARCHAR(20) NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_detections_camera
        FOREIGN KEY (camera_id)
        REFERENCES cameras(id)
);

CREATE INDEX IF NOT EXISTS ix_detections_plate_number
    ON detections (plate_number);


CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detection_id INTEGER NOT NULL,
    camera_id INTEGER NOT NULL,
    plate_number VARCHAR(20) NOT NULL,
    alert_type VARCHAR(50) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    timestamp TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_alerts_detection
        FOREIGN KEY (detection_id)
        REFERENCES detections(id),

    CONSTRAINT fk_alerts_camera
        FOREIGN KEY (camera_id)
        REFERENCES cameras(id)
);

CREATE INDEX IF NOT EXISTS ix_alerts_plate_number
    ON alerts (plate_number);